cybersec:
  - https://news.ycombinator.com/rss
  - https://feeds.feedburner.com/TheHackersNews

technology:
  - https://feeds.arstechnica.com/arstechnica/index/
  - https://lwn.net/headlines/newrss

blockchain:
  - https://cryptonews.com/feed/
  - https://thenewscrypto.com/feed/
  