cybersec:
  - https://news.ycombinator.com/rss
  - https://feeds.feedburner.com/TheHackersNews

technology:
  - https://feeds.arstechnica.com/arstechnica/index/
  - https://lwn.net/headlines/newrss
  - https://www.phoronix.com/rss.php
  - https://hackaday.com/feed

blockchain:
  - https://cryptonews.com/feed/
  - https://thenewscrypto.com/feed/
  
